# Generated by Django 3.1.4 on 2021-05-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Phone_number', models.IntegerField(max_length=10)),
                ('State', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('Supply_address', models.TextField(max_length=200)),
                ('Description', models.TextField(default='', help_text='500 words max', max_length=1000)),
                ('Approx_quantity_available', models.IntegerField(max_length=10)),
            ],
        ),
    ]
